CREATE TABLE MYTABLE (
     OID IDENTITY, -- GENERATED ALWAYS AS IDENTITY
     NAME VARCHAR(50),
     DESCRIPTION VARCHAR(512),
     STATUS VARCHAR(32) NOT NULL DEFAULT 'PENDING',
	PRIMARY KEY (OID)
);

INSERT INTO MYTABLE (
    NAME, DESCRIPTION, STATUS
) VALUES (
    'name1', 'A description', 'PENDING'
);
