micronaut:
  application:
    name: testh2
datasources:
  default:
    url: jdbc:h2:file:./data/h2/mytable.h2;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    dialect: H2
flyway:
  datasources:
    default:
      enabled: true
      locations:
        - classpath:h2-table